### ISSUE TITLE
Access to specific frames, performance. A proposal on introducing a new API

### ISSUE THREAD

**Issue by Krzysztofz01** [AlexEidt/Vidio#6]
Yesterday i forked the ***Vidio*** repository in order to experiment with the `Read()` function.
One of the projects on which I'm working is using ***Vidio*** in a few separate steps:
- First we open a video file to perform an analysis step on all frames and later the program is processing the data and is returning a collection of frame numbers.
- Then I needed to repeat the iteration over the whole video in order to access and export the specified frames.

The iteration over the whole video takes a lot of time due to the `frameBuffer` writing operation. Here is a solution that I tried to implement:

I created a `ReadOffset(n int)` function, that skips *n* frames and writes the *n+1* frame to the `frameBuffer`. The `io.ReadFull` involves the creation of a buffer and the main goal was to prevent allocations and unnecessary writing. The usage of `io.SkipN` with the source set to `video.pipe` and destination `io.Discard` performed the same on the benchmark and profiling that i performed. Later, I thought about using the `Seek()` operation, but the pipe is `ReadCloser` and not `ReadSeekCloser`, and a cast would not help, because we are not waiting for the command to end, so the length is changing and some unexpected bahabiour may occur.

All these problems lead to the idea of introducing a separate API. I think that accessing a specific frame is a common operation and iteration over the whole video file is overkill, especially when we know the specific frame numbers. Also, these kinds of changes: 
- **DO NOT** expose the underlying FFMpeg implementation details, so the API would still seem FFMpeg agnostic
- **DO NOT** change the existing API so no breaking changes will be made
- allow to increase efficiency of applications using ***Vidio***

I though about functions like
```go
GetFrame(filename string, index int) *image.RGBA

GetFrames(filename string, index ...int) []*image.RGBA
```

The underlying FFMpeg API can use the `select` flag. Example flag value to export frames 2, 5 and 10:
```sh
... select='eq(n\,1)+eq(n\,4)+eq(n\,9)' ...
``` 

I would appreciate your opinion on this case and would be happy to implement these changes if my proposal is accepted.

Thank you for creating and maintaining this library.
Best regards!

**Comment by AlexEidt** [comment]
Hi Krzysztof, your proposal sounds good. Adding frame seeking was something I wanted to add, but never got around to.

For the functions you proposed `GetFrame` and `GetFrames`, would those take in a video file name and then return an `*image.RGBA`?

I think the next step would be to outline what specific functions would be implemented and their signatures and we can go from there.

**Comment by Krzysztofz01** [comment]
> For the functions you proposed GetFrame and GetFrames, would those take in a video file name and then return an *image.RGBA?

Yes, i tought about two functions.
`GetVideoFrame(filepath string, n int) (*image.RGBA, error)`
`GetVideoFrames(filepath string, n ...int) ([]*image.RGBA, error)`

​The first one accepts the path to the video file and the index of the frame, it will return the RGBA image pointer.
The second one has a variadic parameter and and will return a slice of RGBA image pointers.


I already started to work on a *test* implementation. I implemented the `GetVideoFrames`  function (and tests). I opened a [pull request](https://github.com/AlexEidt/Vidio/pull/7) in order to show and discuss some details. Currently I'm doing a research on multiple frames export. The `-vf select` flag allows to specify multiple frames  but I have to reverse engineer the order of the frames, because something seems off for now when I perform a diff check on the hexdump of the image buffers. The naive approach would be to run `GetVideoFrame` in a loop, but this approach will spawn a new `cmd` instance for each frame, and the amount of IO operations was the think that I wanted to reduce in the first place.

**Comment by AlexEidt** [comment]
Looks good to me. One comment though, I'd like to keep a consistent interface between all library functions so instead of returning an `*image.RGBA`, the user should pass in an optional array of bytes (as done in `vidio.Read` for images) that the function will fill in with frame data.

Thanks for your work.

**Comment by Krzysztofz01** [comment]
> I'd like to keep a consistent interface between all library functions so instead of returning an `*image.RGBA`, the user should pass in an optional array of bytes

I changed this function as recommended and added some buffer size validation.

Since the preferred way to get results in this type of function is to write the result into the provided buffer, how do we solve the problem of the function to extract multiple frames?
The function would accept arrays of buffers to write frame data, or would it return an array of frame buffers?

We can also not implement it at all and handle such situations by calling `GetVideoFrame()` in a loop. This approach, however spawns separate `cmd`'s  for each frame.

**Comment by Krzysztofz01** [comment]
I prepared a quick implementation of `GetVideoFrames(filepath string, buffers [][]byte, n int...) error``, in order to be able to run benchmarks. The benchmarks consisted of exporting the first and last frames of the video. A recording containing 410 frames (25fps) with a resolution of 1920x1080 was used for testing. The benchmark was run for:
- the current, classic approach, that is, iterating over the entire recording,
- calling `GetVideoFrame()` in a loop,
- calling `GetVideoFrames()`

It seems we can double the performance :)

```
[ 12:03:02 ] krzysztof λ Vidio -> go test -bench=. -benchtime=100x -cpu 4 -benchmem -run=^#
goos: linux
goarch: amd64
pkg: github.com/AlexEidt/Vidio
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkFirstAndLastFrameVideoRead-4        	     100	  46142559 ns/op	  266792 B/op	       1 allocs/op
BenchmarkFirstAndLastFrameGetVideoFrame-4    	     100	  43257306 ns/op	  184913 B/op	       7 allocs/op
BenchmarkFirstAndLastFrameGetVideoFrames-4   	     100	  23941246 ns/op	  184296 B/op	       4 allocs/op
PASS
ok  	github.com/AlexEidt/Vidio	23.519s
[ 12:04:23 ] krzysztof λ Vidio -> 

```

**Comment by AlexEidt** [comment]
Great work Krzysztof! That performance gain is impressive and your added functions solve the seeking problem very well. 

The `GetVideoFrames` function should take in an array of buffers just as you mentioned in the previous comment. The `GetVideoFrames` function looks good to go for me. Add it to the PR and make sure to update the README (I think under the 'VideoWriter' section would be a good place to talk about Seeking) and feel free to add an example showing the seeking. Once that's in I'll merge it.

Thanks again for your quality work and attention to detail!

**Comment by Krzysztofz01** [comment]
> Originally, I thought the `GetVideoFrames` function should take in an array of buffers just as you mentioned in the previous comment. However I thought of the use cases of this function and it's unlikely that someone is going to call a function like that in a loop where the buffer allocations would hurt performance. **I think for `GetVideoFrames` it might be best to return an array of buffers since it's more convenient.** It would be rather unwieldly to allocate all those buffers just to call that function. I think calling `GetVideoFrames` in a loop is definitely an edge case, the more common case would just be to extract frames from a single file and also, it's unlikely that someone is going to want to extract the same N frames from multiple videos. Let me know your thoughts.

I agree. One of the purposes of the `GetVideoFrames` function is to avoid using loops, so this function is unlikely to ever appear in a loop. So I reworked it in such a way that it takes `n ...int` and returns `([][]byte, error)`  


> I was also thinking if the `GetVideoFrame` and `GetVideoFrames` functions could be added as functions for the `Video` struct ...

Good point, in recent commits I moved this functionality to the `Video` struct. I managed, thanks to that, to remove the repetitive code. However, I also made changes to the name of these functions to better match the `Video` struct API.

`GetVideoFrame(filename string, n int, frameBuffer []byte) error` changed into
`ReadFrame(n int) error`

and

`GetVideoFrames(filename string, n ...int, frameBuffers [][]byte)` changed into
`ReadFrames(n ...int) ([][]byte, error)` 





> ... make sure to update the README and feel free to add an example showing the seeking.

I updated the README and added two examples in [this commit](https://github.com/AlexEidt/Vidio/pull/7/commits/4fe8cad5092e668f50b41c584b215c432413da13).

**Comment by AlexEidt** [comment]
Looks good.

Apologies for going back and forth on this, however I was thinking that returning `[]*image.RGBA` for `ReadFrames` might be preferable since the user would directly have access to an `image.RGBA` and could also access the `Pix` if they wanted the raw bytes since we're allocating the buffers anyways. With the `[][]byte` the user would have to copy each buffer if they wanted `image.RGBA` structs.

Additionally the `buildSelectExpression` should be moved into `utils.go`.

**Comment by Krzysztofz01** [comment]
> ... `[]*image.RGBA` for `ReadFrames` might be preferable ...

Good point, it was evident in the tests themselves. Returning the results as `[]*image.RGBA` would certainly be more convenient. I made the suggested change in [this commit](https://github.com/AlexEidt/Vidio/pull/7/commits/f6a2909ea328d6b55689cc1c95f59498a81b1864)


> Additionally the `buildSelectExpression` should be moved into `utils.go`.

Done, change implemented ([commit](https://github.com/AlexEidt/Vidio/pull/7/commits/a1d63d0f9fcd5d9912cf0f836cd2ec840c9d55d5))

**Comment by AlexEidt** [comment]
Merged and created a new release for the changes. Thanks again for your work, the seeking functionality is great.

**Comment by Krzysztofz01** [comment]
Thank you for working together and for merging the pull request 😃
