### ISSUE TITLE
Get video extension

### ISSUE THREAD

**Issue by JonatanAlcaraz** [AlexEidt/Vidio#9]
I have a route which receives a video through an http post, basically what I want is to validate the extension of this video to only work with mp4 videos. Can I do this?

**Comment by AlexEidt** [comment]
The library does not support downloading videos on the web. It only works with video files in your file system.

You could download the mp4 video and then use this library to check that it is valid.

```go
// Some other code downloads the video via http post and saves as "video.mp4".

// Read the downloaded video.
video, _ := vidio.NewVideo("video.mp4")

// Get metadata from video and check to see if it's what you expected.
width := video.Width();
height := video.Height();
fps := video.FPS();
// ...

```

Let me know if that answers the question.
